### ISSUE TITLE
checkpoint is not available

### ISSUE THREAD

**Issue by casioexlim** [jzmzhong/Automatic-Prosody-Annotator-with-SSWP-CLAP#1]
Thanks a lot for your great work.
Your checkpoit "finetuned_prosody_annotator.pt "  can not be downloaded because of 
your repository is over  data quota.

would you please upload it to google cloud?

**Comment by jzmzhong** [comment]
Hi!

The checkpoint is uploaded using git LFS. You may try to access the checkpoint in two ways:

1) by git LFS
git lfs install
git lfs fetch origin master

2) by google cloud
The model is alternatively available at: https://drive.google.com/file/d/1S2qzepfFp2kpeB20678NLILLmH_Xt1WR/view?usp=sharing
The downloaded checkpoint should be placed at ./released_model/finetuned_prosody_annotator.pt


Please let us know if there are any other issues! Thank you!

**Comment by casioexlim** [comment]
> Hi!
> 
> The checkpoint is uploaded using git LFS. You may try to access the checkpoint in two ways:
> 
>     1. by git LFS
>        git lfs install
>        git lfs fetch origin master
> 
>     2. by google cloud
>        The model is alternatively available at: https://drive.google.com/file/d/1S2qzepfFp2kpeB20678NLILLmH_Xt1WR/view?usp=sharing
>        The downloaded checkpoint should be placed at ./released_model/finetuned_prosody_annotator.pt
> 
> 
> Please let us know if there are any other issues! Thank you!

Great ! Thanks a lot !

**Comment by casioexlim** [comment]
> Hi!
> 
> The checkpoint is uploaded using git LFS. You may try to access the checkpoint in two ways:
> 
>     1. by git LFS
>        git lfs install
>        git lfs fetch origin master
> 
>     2. by google cloud
>        The model is alternatively available at: https://drive.google.com/file/d/1S2qzepfFp2kpeB20678NLILLmH_Xt1WR/view?usp=sharing
>        The downloaded checkpoint should be placed at ./released_model/finetuned_prosody_annotator.pt
> 
> 
> Please let us know if there are any other issues! Thank you!

Great ! Thanks a lot !
